/**
 * ConversationState
 * Defines the explicit finite state machine steps for the GasBot conversational flow.
 */
export enum ConversationState {
  IDLE = 'IDLE',
  LANGUAGE_SELECT = 'LANGUAGE_SELECT',
  ROLE_SELECT = 'ROLE_SELECT',
  MAIN_MENU = 'MAIN_MENU',
  PRODUCT_SELECT = 'PRODUCT_SELECT',
  CONFIRM_PRODUCT = 'CONFIRM_PRODUCT',
  BOTTLE_IMAGE_UPLOAD = 'BOTTLE_IMAGE_UPLOAD',
  LOCATION_INPUT = 'LOCATION_INPUT',
  LOCATION_SHARE_CHOICE = 'LOCATION_SHARE_CHOICE',
  ORDER_SUMMARY = 'ORDER_SUMMARY',
  CASH_ACKNOWLEDGEMENT = 'CASH_ACKNOWLEDGEMENT',
  SUPPLIER_REGISTRATION = 'SUPPLIER_REGISTRATION',
  SUPPLIER_REVIEW = 'SUPPLIER_REVIEW',
  SUPPLIER_NOTIFICATION_RESPONSE = 'SUPPLIER_NOTIFICATION_RESPONSE',
}
